version: "2"
run:
  timeout: 5m
  tests: true

linters:
  default: all
  disable:
    - depguard
    - godox
  settings:
    cyclop:
      max-complexity: 15
    gocyclo:
      min-complexity: 15 # Set the threshold for cyclomatic complexity
    misspell:
      locale: US # Use US English for spell checking
    revive:
      rules:
        - name: package-comments
          severity: warning
          disabled: true

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true
